from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 599)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 70, 1011, 451))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 992, 1000))
        self.scrollAreaWidgetContents_2.setMinimumHeight(1000)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.kartka1 = QtWidgets.QWidget(self.widget_4)
        self.kartka1.setGeometry(QtCore.QRect(10, 0, 271, 411))
        self.kartka1.setStyleSheet("background-color: rgb(111, 106, 255);")
        self.kartka1.setObjectName("kartka1")
        self.rait = QtWidgets.QLabel(self.kartka1)
        self.rait.setGeometry(QtCore.QRect(120, 10, 75, 16))
        self.rait.setObjectName("rait")
        self.date = QtWidgets.QLabel(self.kartka1)
        self.date.setGeometry(QtCore.QRect(220, 10, 50, 16))
        self.date.setObjectName("date")
        self.name = QtWidgets.QLabel(self.kartka1)
        self.name.setGeometry(QtCore.QRect(9, 9, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.name_4 = QtWidgets.QLabel(self.kartka1)
        self.name_4.setGeometry(QtCore.QRect(0, 30, 271, 411))
        self.name_4.setText("")
        self.name_4.setPixmap(QtGui.QPixmap("../../Desktop/MovieStorageApp-main/images/Interstellar_film_poster2.jpg"))
        self.name_4.setScaledContents(True)
        self.name_4.setObjectName("name_4")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setGeometry(QtCore.QRect(340, 0, 281, 411))
        self.widget_2.setStyleSheet("background-color: rgb(111, 106, 255);")
        self.widget_2.setObjectName("widget_2")
        self.rait_2 = QtWidgets.QLabel(self.widget_2)
        self.rait_2.setGeometry(QtCore.QRect(120, 10, 75, 16))
        self.rait_2.setObjectName("rait_2")
        self.date_2 = QtWidgets.QLabel(self.widget_2)
        self.date_2.setGeometry(QtCore.QRect(220, 10, 50, 16))
        self.date_2.setObjectName("date_2")
        self.name_2 = QtWidgets.QLabel(self.widget_2)
        self.name_2.setGeometry(QtCore.QRect(10, 9, 69, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.name_2.setFont(font)
        self.name_2.setObjectName("name_2")
        self.name_5 = QtWidgets.QLabel(self.widget_2)
        self.name_5.setGeometry(QtCore.QRect(0, 30, 281, 411))
        self.name_5.setText("")
        self.name_5.setPixmap(QtGui.QPixmap("../../Desktop/MovieStorageApp-main/images/2007399.jpg"))
        self.name_5.setScaledContents(True)
        self.name_5.setObjectName("name_5")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setGeometry(QtCore.QRect(670, 0, 281, 411))
        self.widget_3.setStyleSheet("background-color: rgb(111, 106, 255);")
        self.widget_3.setObjectName("widget_3")
        self.rait_3 = QtWidgets.QLabel(self.widget_3)
        self.rait_3.setGeometry(QtCore.QRect(120, 10, 75, 16))
        self.rait_3.setObjectName("rait_3")
        self.date_3 = QtWidgets.QLabel(self.widget_3)
        self.date_3.setGeometry(QtCore.QRect(200, 10, 50, 16))
        self.date_3.setObjectName("date_3")
        self.name_3 = QtWidgets.QLabel(self.widget_3)
        self.name_3.setGeometry(QtCore.QRect(10, 9, 69, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.name_3.setFont(font)
        self.name_3.setObjectName("name_3")
        self.name_6 = QtWidgets.QLabel(self.widget_3)
        self.name_6.setGeometry(QtCore.QRect(0, 30, 281, 381))
        self.name_6.setText("")
        self.name_6.setPixmap(QtGui.QPixmap("../../Desktop/MovieStorageApp-main/images/Початок_фільм,_2010.jpg"))
        self.name_6.setScaledContents(True)
        self.name_6.setObjectName("name_6")
        self.kartka1_2 = QtWidgets.QWidget(self.widget_4)
        self.kartka1_2.setGeometry(QtCore.QRect(9, 419, 271, 403))
        self.kartka1_2.setStyleSheet("background-color: rgb(111, 106, 255);")
        self.kartka1_2.setObjectName("kartka1_2")
        self.rait_6 = QtWidgets.QLabel(self.kartka1_2)
        self.rait_6.setGeometry(QtCore.QRect(120, 10, 75, 16))
        self.rait_6.setObjectName("rait_6")
        self.date_6 = QtWidgets.QLabel(self.kartka1_2)
        self.date_6.setGeometry(QtCore.QRect(220, 10, 50, 16))
        self.date_6.setObjectName("date_6")
        self.name_11 = QtWidgets.QLabel(self.kartka1_2)
        self.name_11.setGeometry(QtCore.QRect(0, 10, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.name_11.setFont(font)
        self.name_11.setObjectName("name_11")
        self.name_12 = QtWidgets.QLabel(self.kartka1_2)
        self.name_12.setGeometry(QtCore.QRect(-10, 30, 281, 371))
        self.name_12.setText("")
        self.name_12.setPixmap(QtGui.QPixmap("../../Desktop/MovieStorageApp-main/images/200px-Fight_Club_плакат.jpg"))
        self.name_12.setScaledContents(True)
        self.name_12.setObjectName("name_12")
        self.kartka1_3 = QtWidgets.QWidget(self.widget_4)
        self.kartka1_3.setGeometry(QtCore.QRect(340, 420, 281, 403))
        self.kartka1_3.setStyleSheet("background-color: rgb(111, 106, 255);")
        self.kartka1_3.setObjectName("kartka1_3")
        self.rait_7 = QtWidgets.QLabel(self.kartka1_3)
        self.rait_7.setGeometry(QtCore.QRect(120, 10, 75, 16))
        self.rait_7.setObjectName("rait_7")
        self.date_7 = QtWidgets.QLabel(self.kartka1_3)
        self.date_7.setGeometry(QtCore.QRect(220, 10, 61, 16))
        self.date_7.setObjectName("date_7")
        self.name_13 = QtWidgets.QLabel(self.kartka1_3)
        self.name_13.setGeometry(QtCore.QRect(9, 9, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.name_13.setFont(font)
        self.name_13.setObjectName("name_13")
        self.name_14 = QtWidgets.QLabel(self.kartka1_3)
        self.name_14.setGeometry(QtCore.QRect(0, 30, 281, 371))
        self.name_14.setText("")
        self.name_14.setPixmap(QtGui.QPixmap("../../Desktop/MovieStorageApp-main/images/225px-Український_постер_фільму__Драйв_.jpg"))
        self.name_14.setScaledContents(True)
        self.name_14.setObjectName("name_14")
        self.kartka1_4 = QtWidgets.QWidget(self.widget_4)
        self.kartka1_4.setGeometry(QtCore.QRect(670, 420, 281, 401))
        self.kartka1_4.setStyleSheet("")
        self.kartka1_4.setObjectName("kartka1_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.kartka1_4)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 160, 121, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"background-color: rgb(170, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.widget_4, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(260, 30, 461, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"background-color: rgb(170, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rait.setText(_translate("MainWindow", "⭐⭐⭐⭐⭐"))
        self.date.setText(_translate("MainWindow", "2023-8-12"))
        self.name.setText(_translate("MainWindow", "Інтерстеллар"))
        self.rait_2.setText(_translate("MainWindow", "⭐⭐⭐⭐"))
        self.date_2.setText(_translate("MainWindow", "2024-10-1"))
        self.name_2.setText(_translate("MainWindow", "Паразити"))
        self.rait_3.setText(_translate("MainWindow", "⭐⭐⭐"))
        self.date_3.setText(_translate("MainWindow", "2024-9-20"))
        self.name_3.setText(_translate("MainWindow", "Початок"))
        self.rait_6.setText(_translate("MainWindow", "⭐⭐⭐⭐⭐"))
        self.date_6.setText(_translate("MainWindow", "2022-8-12"))
        self.name_11.setText(_translate("MainWindow", "Бійцівський клуб"))
        self.rait_7.setText(_translate("MainWindow", "⭐⭐⭐⭐⭐"))
        self.date_7.setText(_translate("MainWindow", "2023-12-12"))
        self.name_13.setText(_translate("MainWindow", "Драйв"))
        self.pushButton_2.setText(_translate("MainWindow", "Додати"))
        self.pushButton.setText(_translate("MainWindow", "Пошук"))
